### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by informaticaeloy** [namecheap/fast_mail_parser#9]
Hello. I am trying to use fast_mail_parser, but i am getting this error:

```shell
Traceback (most recent call last):
  File "e:\DESARROLLO\Mail Analyzer\prueba.py", line 4, in <module>
    from fast_mail_parser import parse_email, ParseError
  File "C:\Users\xxxxxxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\fast_mail_parser\__init__.py", line 31, in <module>
    from .fast_mail_parser import parse_email, ParseError
ImportError: DLL load failed while importing fast_mail_parser: El parámetro no es correcto.
```

the code that i am using is the official code of the samples in github:

```python


import sys
from fast_mail_parser import parse_email, ParseError
 
with open('./solo_eml_file.eml', 'r') as f:
    message_payload = f.read()
 
try:
    email = parse_email(message_payload)
except ParseError as e:
    print("Failed to parse email: ", e)
    sys.exit(1)
 
print(email.subject)
print(email.date)
print(email.text_plain)
print(email.text_html)
print(email.headers)

for attachment in email.attachments:
    print(attachment.mimetype)
    print(attachment.content)

```

Can you help me, please? thanks

**Comment by sokyrko** [comment]
Hi.
What Windows and Python versions you use?

**Comment by informaticaeloy** [comment]
Hi. 
Windows 10 pro 22H2, python 3.10.10, VS 1.76.0 and fast_mail_parser 0.2.5
txs

**Comment by sokyrko** [comment]
I'm glad it worked!
Close the issue then please.

**Comment by informaticaeloy** [comment]
Sure. Great job. I am doing email reports using your code. Thanks.
